<?php

namespace ColeThorsen\USPS\Enums;

enum MailClass: string
{
    // Domestic Mail Classes
    case GROUND_ADVANTAGE          = 'GROUND_ADVANTAGE';
    case PRIORITY_MAIL             = 'PRIORITY_MAIL';
    case PRIORITY_MAIL_EXPRESS     = 'PRIORITY_MAIL_EXPRESS';
    case FIRST_CLASS_MAIL          = 'FIRST_CLASS_MAIL';
    case PARCEL_SELECT             = 'PARCEL_SELECT';
    case PARCEL_SELECT_LIGHTWEIGHT = 'PARCEL_SELECT_LIGHTWEIGHT';
    case MEDIA_MAIL                = 'MEDIA_MAIL';
    case LIBRARY_MAIL              = 'LIBRARY_MAIL';
    case BOUND_PRINTED_MATTER      = 'BOUND_PRINTED_MATTER';
    case CONNECT_LOCAL             = 'CONNECT_LOCAL';

    // International Mail Classes
    case PRIORITY_MAIL_INTERNATIONAL         = 'PRIORITY_MAIL_INTERNATIONAL';
    case PRIORITY_MAIL_EXPRESS_INTERNATIONAL = 'PRIORITY_MAIL_EXPRESS_INTERNATIONAL';
    case FIRST_CLASS_MAIL_INTERNATIONAL      = 'FIRST_CLASS_MAIL_INTERNATIONAL';
    case FIRST_CLASS_PACKAGE_INTERNATIONAL   = 'FIRST_CLASS_PACKAGE_INTERNATIONAL';
}
